#!/usr/bin/env python3
"""Copy summarize-anything outputs from research-material into the site and
build _data/summaries.yml. Source URL is parsed from the summary metadata.
The source PDF is only copied when no source URL was found (keeps the repo lean
while still guaranteeing a link to the source)."""
import json, os, re, shutil, time

SRC = "/home/nik/research-material"
REPO = "/home/nik/research-digest"
DEST = os.path.join(REPO, "summaries")
MANIFEST = os.path.join(REPO, "_data", "summaries.yml")


def find_url(*texts):
    blob = " ".join(t for t in texts if t)
    m = re.search(r"https?://[^\s\"'<>)]+", blob)
    if m:
        return m.group(0).rstrip(".,);")
    m = re.search(r"(?:IACR\s+)?ePrint\s+(\d{4})/(\d+)", blob, re.I)
    if m:
        return "https://eprint.iacr.org/%s/%s" % (m.group(1), m.group(2))
    m = re.search(r"arXiv[:\s]+(\d{4}\.\d{4,5})", blob, re.I)
    if m:
        return "https://arxiv.org/abs/%s" % m.group(1)
    m = re.search(r"\b(10\.\d{4,9}/[^\s\"'<>]+)", blob)
    if m:
        return "https://doi.org/%s" % m.group(1).rstrip(".,);")
    return ""


def clean(s):
    """Display text: no em or en dashes (site style)."""
    return (s or "").replace("—", " - ").replace("–", "-").strip()


def yaml_escape(s):
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def slug_date(slug, fallback):
    m = re.search(r"(\d{4}-\d{2}-\d{2})$", slug)
    return m.group(1) if m else fallback


def main():
    os.makedirs(DEST, exist_ok=True)
    entries = []
    for root, _dirs, files in os.walk(SRC):
        if "summary.html" not in files or "content.json" not in files:
            continue
        slug = os.path.basename(root)
        try:
            meta = json.load(open(os.path.join(root, "content.json")))
        except Exception:
            meta = {}
        title = clean(meta.get("title") or slug)
        source_type = clean(meta.get("source_type") or "")

        html = ""
        try:
            html = open(os.path.join(root, "summary.html"), encoding="utf-8").read(8000)
        except Exception:
            pass
        source_url = find_url(source_type, json.dumps(meta.get("sections", ""))[:4000], html)

        out = os.path.join(DEST, slug)
        shutil.rmtree(out, ignore_errors=True)
        os.makedirs(out, exist_ok=True)
        shutil.copyfile(os.path.join(root, "summary.html"), os.path.join(out, "index.html"))
        if os.path.isdir(os.path.join(root, "assets")):
            shutil.copytree(os.path.join(root, "assets"), os.path.join(out, "assets"))

        pdf = ""
        if not source_url and os.path.isfile(os.path.join(root, "source.pdf")):
            shutil.copyfile(os.path.join(root, "source.pdf"), os.path.join(out, "source.pdf"))
            pdf = "/summaries/%s/source.pdf" % slug

        try:
            mtime = time.strftime("%Y-%m-%d", time.gmtime(os.path.getmtime(os.path.join(root, "summary.html"))))
        except Exception:
            mtime = ""

        tags = meta.get("tags") or []
        if not isinstance(tags, list):
            tags = []
        entries.append({
            "slug": slug, "title": title, "source_type": source_type,
            "source_url": source_url, "pdf": pdf, "tags": tags,
            "url": "/summaries/%s/" % slug, "date": slug_date(slug, mtime),
        })

    entries.sort(key=lambda e: e["date"], reverse=True)
    lines = [
        "# Published summaries. Generated by automation/publish-summaries.py.",
        "# Do not edit by hand; rerun the publisher.",
        "",
    ]
    for e in entries:
        for k in ("slug", "title", "url", "date", "source_type", "source_url", "pdf"):
            prefix = "- " if k == "slug" else "  "
            lines.append('%s%s: "%s"' % (prefix, k, yaml_escape(e[k])))
        tag_items = ", ".join('"%s"' % yaml_escape(t) for t in e.get("tags", []))
        lines.append('  tags: [%s]' % tag_items)
    open(MANIFEST, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("published %d summaries -> %s" % (len(entries), MANIFEST))


if __name__ == "__main__":
    main()
